name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow mannually trigger
permissions: write-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Codespaces container image
      run: docker build . --file .devcontainer/Dockerfile


    # steps:  
    # - name: Checkout Repository  
    #   uses: actions/checkout@v3  
    
    # - name: Set Up Docker Build Arguments  
    #   run: echo "BUILD_VERSION=${{ github.sha }}" >> $GITHUB_ENV # Set build version from commit SHA  
    
    # - name: Build Docker Image  
    #   run: |  
    #     docker build . \
    #       --file .devcontainer/Dockerfile \
    #       --tag my-docker-image:${{ env.BUILD_VERSION }} # Tag the image with the commit SHA  
    
    # - name: Verify Docker Image  
    #   run: docker images # List the Docker images to verify the build  
